export const metadata = {
  title: "About | Next App First",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div>
      <h3>Select subitems</h3>
    </div>
  );
}
