export const metadata = {
  title: "Contacts | Next App First",
  description: "Generated by create next app",
};

export default function Contacts() {
  return (
    <div>
      <h1>Contacts page</h1>
    </div>
  );
}
