export const metadata = {
  title: "Team | Next App First",
  description: "Generated by create next app",
};

export default function Team() {
  return (
    <div>
      <h1>Team page</h1>
    </div>
  );
}
